#include "../../defines.h"
#include <string>
#include "../../Dcx.h"
#include "../tinyxml/tinyxml.h"
#include "../dcxdialog.h"
#include "../dcxdialogcollection.h"
#include "../dcxcontrol.h"
#include <map>
#include "../xpopup/xpopupmenumanager.h"