#include "defines.h"
#include <string>
#include "Dcx.h"
#include "Classes/tinyxml/tinyxml.h"
#include "Classes/dcxdialog.h"
#include "Classes/dcxdialogcollection.h"
#include "Classes/dcxcontrol.h"
#include <map>
#include "Classes/xpopup/xpopupmenumanager.h"
