<?php
$CHANGES = array(
    'v1.4.0' => array(
        'New features' => array(
            'added DCXML',
            "added a dialog callback called 'zlayershow'",
            'added /xdid -V for listview which scrolls list to make an item visible',
            'added /xdid -P for (rich)edit to paste clipboard content',
            'added +o flag for /xdock -b to use the old style treebar docking',
            'added /xdialog -P to use xpopup commands on dialog menus',
            "added /xstatusbar to dock a statusbar into mIRC's main window",
            "added /xtreebar to modify mIRC's treebar",
            'added +t flag to /xdid -i for image control to tile the image',
            'added /xdid -w for stacker to add images to internal imagelist',
            'added /xdid -y for stacker which clears the internal image list',
            'added /xdid -o for image control to offset picture',
            "added general 'noformat' style to disable support for mIRC formatted text in some controls",
            'added /xdid +k -1 for statusbar to reset color',
            'added +f flag to /xdid –t for statusbar to display formatted mIRC text',
            'added +c flag to /xdid –t for statusbar to create child controls',
            'added text support to line control',
            'added /xdid -a for text control to append text',
            'icon loading supports +a flag to show associated filetype icon if icon fails to load from specified file',
            'added animate styles to /xdid -h and /xdid –s',
            '/xdid -R +f can now be combined with the +R flag so image is resized to control size before applying region',
            "added 'alpha' support to treeview",
            "added 'alpha' support to trackbar",
            'added $xdid().isloaded property to directshow to determine if a file is loaded',
            'added +b flag to /xdock -n to disable scrollbars',
            'added $xdid().fname for directshow to get loaded filename',
            'added $xdid().fname for image to get loaded filename',
            "added 'closable' style for tab control to add X button on tab items",
            "added 'gradient' style for tab for gradient item background",
            "added 'closetab' event for tab control when the close button is clicked",
            'added +a flag to /xdid -a for directshow which specifies audio only',
            "added 'noheadersort' style to listview",
            'added /xpopup -R rounded style and ability to set transparency level',
            'added $xpopup().isrounded',
            'added $xpopup().alpha',
            'added $dcx(PickIcon, index filename) to open an icon selector on XP+',
            'added $xdid().wname for docked @window control to retrieve window name',
            "added 'SelectedText' colour (index 11) to xpopup menus",
            'added +r flag for /xdid -C to set border colour',
            'added +b flag for /xdid -R to set control alpha blending level',
            'added +v flag for /xdialog -b to set vista styled dialog (2k+) (WARNING: uses extremely high processing power on older machines)',
            '/xdialog -t now allows setting of alpha value and transparent colour',
            'added /xdialog -V to adjust the vista aero glass area',
            'added $dcx(ActiveWindow) to retrieve properties of the currently active window within operating system',
            'added /xdid -v for tab control which moves an item to a new position',
            'added /xdid -l for edit to change readonly state',
            'added $xdid().isreadonly to edit control',
            'added xdid -r for text control to clear text',
            "added 'returndefault' style to ColorDialog",
            "added 'draglist' style to list control",
            'added callbacks itemdragbegin, itemdragcancel, itemdrag, itemdragfinish to list control',
            "added 'dragline' style to list control",
            'added support for a background image via /xdid -G for treeview',
            "added 'selected' and 'deselected' events to listview",
            "added 'selchange' event to treeview",
            "added 'showsel' and 'noshowsel' to /xdock -F +s styles (now moved to /xtreebar +s)",
            "added 'sizing' event to tab control",
            'added /dcx WindowProps +r to simulate a right click',
            'added $xtreebar().item to retrieve text from mIRC Treebar',
            'changed statusbar /xdid -l to accept percentage values as valid widths. values without the % symbol are considered fix widths',
            "added 'noauto' style to statusbar",
            "added 'noauto' style to rebar",
            'allowed divier to host all control types',
            "added 'showsel' style to edit",
            'allowed statusbar to host all control types',
            "added 'keydown' event to listview",
            "added general style 'hidden' to all controls except mdialog and mwindow",
            "added 'alpha' style to tab",
            'added /xdid -y to enable/disable keydown events for button being held down',
            'added listview /xdid -W This command lets you change the viewing mode',
            'added overlay icon support to treeview and listview',
            'added $xdid(listview).columnorder to get the order of the columns',
            'added listview +m flag to /xdid -n to allow manual width specification for all widths at once',
            "added dialog callback 'isverbose' which is sent as soon as a dialog is marked",
            'added listview /xdid -o to allow user to change column order',
            'added VALUE to sclick, rclick and mousebar as they were in docs (but not included in code)',
            'when space is pressed and checkboxes enabled, stateclick event will be triggered',
            "'nospace' is accepted as a return value for 'keydown' to prevent the user from using the spacebar to change checkbox values",
        ),
        'Syntax changes' => array(
            'updated dcx_tools.mrc to include /xstatusbar and /xtreebar aliases',
            'moved statusbar and treeview commands from /xdock to /xstatusbar and /xtreebar',
            'changed stacker /xdid -a to support image indexes',
            'changed listview /xdid -a to include OVERLAY, COLOR and BGCOLOR (for subitems)',
            'changed listview /xdid -j to include COLOR and BGCOLOR (optional parameters)',
            'changes to icon loading commands such as /xdid -w to support icon flags which affect most controls',
            'changed /xpopup -i to support flags',
            '/xtray now supports (and hence requires) icon flags',
            "changed \$xdock(mIRC) switchBarSize, toolBarSize and treeBarSize to return 'x y w h' instead of just 'w h'",
            'changed statusbar /xdid -l to take widths instead of border offsets',
            'moved /xdock -G to /dcx GhostDrag',
            "changed \$xstatusbar properties; 'isStatusBar' to 'visible', 'statusText' to 'text', 'statusParts' to 'parts' and 'statusTooltip' to 'tooltip'",
            'modified (rich)edit /xdid -S to make END parameter optional (to change caretpos)',
            'mwindow now accepts HWND as well as @window name for docking',
            "the 'changing' callback event for dialogs now include sizing, moving or both to determine which event occurred and the dialog sizes.",
            '/dcx xSignal changed to support optional flags +dst (xdock, xstatusbar, xtray)',
            'changed treeview and listview /xdid -w to allow setting an icon as an overlay icon. READ NOTES!',
            'listview /xdid -l now supports optional parameter OVERLAY',
            'changed [N] to be an optional parameter in $xdid(listview).hwidth so all widths are returned',
            '$xdid(lv).text parameter NSUB is now 1-based index',
            '$xdid(lv).icon parameter NSUB is now 1-based index',
            '$xdid(lv).seltext parameter NSUB is now 1-based index',
            '$xdid(lv).seltext NSUB is now optional, returns first column by default',
            'listview /xdid -n parameter COL is now 1-based index',
            'listview /xdid -v parameter COL is now 1-based index',
            'modified treeview /xdid -j to support overlays',
            "added header ID to listview 'trackbegin' event",
            'switched EVENT and DCXStatusBar parameters in XStatusBar signals',
            "dialog 'close' event has been broken up into 'close' and 'scclose' to provide better control",
            'made $xdid(listview, N, NSUB).text NSUB parameter optional (returns first column by default)',
            'listview events stateclick/sclick/dclick/rclick/rdclick/hover/selected/deselected SUBITEM index is now 1-based indexes',
            'listview event labelbegin now provides N and NSUB',
            'colorcombo /xdid -c now accepts 0 to clear selection (thanks andy for idea)',
            'moved VALUE param to the end of events (no syntax changes required)',
        ),
        'Fixes and changes' => array(
            "added check for correct flags prefix '+' in image control xdid -i",
            'added /xdid -Z as a temporary fix until the -Z listview problem is fixed',
            'changed WM_CTLCOLOR message parsing so they work correctly when a background brush is not set (fixed /xdid -C bug)',
            'changed AdjustMDIRect() to reserve space for docked dialogs only if they are visible. This has a side effect in that dialogs docked within the init event never have the visible flag set so show up wrong, This is fixed by using a timer',
            'changed /xdialog -x to send WM_CLOSE instead of using DestroyWindow()',
            'changed /xdid -T to use ListView_SetInfoTip()',
            'added fix for 1px images being stretched',
            'changed $xdid().text to use a 1-based index for parameter N',
            'fixed directshow $xdid().currentpos',
            'changed directshow /xdid -a to InvalidateRect() after loading media',
            'fixed listview bold/underline/etc flags being misapplied to subitems',
            'fixed /xdid -a stacker check for numtok',
            'image fixed background updating when transparent.',
            'fixed /dcx WindowProps check for -FLAG to +FLAG',
            'fixed the box border style when no text is supplied',
            'changed listview /xdid -a to check for nPos < 0 rather than == -1',
            'changed stacker WM_DRAWITEM to only set back mode to TRANSPARENT when doing non-formatted text rendering',
            'changed statusbar /xdid -t to check for an invalid part and give an error',
            'changed statusbar /xdid -v to give an error when an invalid part is supplied',
            'changed mdialog to set back to OrigID in destroy, instead of setting to ID',
            '/xdid -h and /xdid -s now update CLA immediately',
            'changed GetHwndFromString() to allow supplying an HWND (allows mdialog/mwindow to dock via the hwnd)',
            'changed /xdialog -d to remove the control from the internal list when its an embedded dialog/window',
            'changed object delete code to set parent differently (this fixes most but not all of the undocking problems)',
            'changed /xdid -J to use LoadImage(IMAGE_CURSOR) and get a non-shared cursor handle (this allows us to delete the cursor and fixed the graphics corruption bug)',
            'changed /xdid -J to check if file exists',
            'changed /xdialog -q to check file exists',
            'changed WM_SETCURSOR code to check if the cursor to set is the same as the current before trying to set',
            'changed pager /xdid -d to remove mdialog or mwindow control from the internal list',
            'changed edit /xdid -j to set the ES_PASSWORD style before getting the char, allowing the XP style to be used instead of always setting to *',
            "small change to some xpopup if's to use a TString compare instead of doing a gettok as well",
            'added a buffer delete to IsFile() to cover the case where the search fails after having found the file the first time',
            'changed /xpopup -b to check a file exists and give an error if it doesnt',
            "changed /xpopup -b to accept 'none' or \$null as a file name to remove current image",
            'changed /xpopup -i to check a file exists and give an error if it doesnt',
            "changed \$xpopup().style to support 'vertical' and 'verticalrev' styles",
            'changed dcxLoadIcon() to use GDI+ when +P is supplied. this allows it to load any GDI+ supported image format as an icon',
            'changed dcxLoadBitmap() to use GDI+ when it can to load the image. this allows all bitmap loading commands to load any GDI+ supported format',
            'fixed incorrect coordinates of toolbar dropdown',
            'changed ChangeHwndIcon() to avoid doing things twice when small and large icons are the same',
            'changed /xpopup -b to trim() the filename',
            "fixed rebar wasn't returning the results from child controls",
            'changed directshow /xdid -a to check for a min of 4 args',
            'added a check for at least 4 args in subitems to listview /xdid -a',
            'changed listview /xdid -t to use the autoSize() function',
            'added check for directx 9 to directshow /xdid -a',
            'fixed trackbar thumb image rendering when selected',
            'changed /xdialog -j to only redraw the whole dialog if an ID isnt specified',
            'changed /xdock -A to halt on error',
            'fixed bug where button text would be forgotten when other buttons were deleted',
            'all dcx controls automatically redraw themselves upon theme change',
            'fixed /xdock -u requiring flags',
            'added background color drawing to panel via /xdid -C',
            'added directshow $xdid().volume to get current volume',
            'added directshow /xdid -V to set volume',
            'added directshow events rbdown, rbup and rclick ',
            'fixed xpopup bug in DrawItemCheckBox() where pen was deleted without first being removed from HDC',
            'fixed duplicate sclick event when clicking on an unselected tab',
            'fixed treeview bug when moving an item to an empty parent',
            'fixed listview $xdid().pbar to work correctly',
            'added code to fix listview font changes per subitem',
            'added code to make sure listview has focus before doing a label edit. No longer need to force focus first',
            'changed ghost drag to use the set alpha level after a drag instead of 255',
            'changed button background drawing a little',
            'changed pbar/image background drawing to only do parents background when transparent',
            'fixed tab bug where incorrect button ID was shown in sclick event',
            'fixed xpopup menu corruption when MDI client (channel) window is maximized then restored',
            'modified checkbox so correct $xdid().state value can be used during sclick event',
            'changed /xdialog -x to only send WM_CLOSE to modal dialogs',
            'added WM_CLOSE check for escape being pressed. Fixes divider being destroyed bug',
            'fixed listview pbars within items scrolling oddly when horizontal scroll is used',
            "changed /xdialog -t alpha and /xdialog -t transparentcolor to accept 'none'",
            'fixed bug with /xtray -i loading the wrong icon index',
            'changed /xdid -U to remove focus from control correctly',
            "changed how the panel and box controls are registered, which fixes the 'no tooltips' and 'label edit' bugs",
            'changed dcxSignal boolean into a finegrained struct',
            'changed mIRCSignalDCX() to require a boolean parameter',
            'changed SystemTimeToMircTime() to use mIRCevalEX()',
            'xtray and xstatusbar signals are now sent by default, but xdock signals are still disabled',
            "fixed calendar 'select' callback for single select",
            'fixed calendar $xdid().value returning 0 for single select',
            "added spaces between names in Version and changed '&' to 'and'",
            'added initImageList() for listview to make icon adding code cleaner',
            'added token count checking to /xdid -j',
            'ColorDialog, OpenDialog, SaveDialog, FontDialog and MsgBox. They no longer support modeless owners due to FindOwner()',
            'fixed /xdid -a so it adds to end if N out of range (thanks andy)',
            'fixed $xdid(listview).sel from appending unecessary comma at the end of list',
            'fixed /xdid -Z, but only for report view',
        ),
        'DCX Project' => array(
            'removed commented code',
            'added TGetWindowText() function which gets the window text as a TString',
            'fix possible memleak with treeview setImageList()',
            "moved some mIRC HWND's into mIRCLink",
            'changed $dcx(GetSystemColor), $dcx(ColorDialog), $dcx(FontDialog) and $dcx(GetTaskbarPos) to avoid an unneeded copy to set the return value',
            'made parseListviewExStyles() and createImageList() static functions',
            'added dcxDock class which handles behaviour',
            'changed UltraDock to use new dcxDock class',
            'added TreebarDock using dcxDock class, which takes the same flags as UltraDock',
            'changed /xdock -b to use the new TreebarDock by default',
            'moved the drawing code for images to DrawBMPImage() and DrawGDIImage()',
            'updated dcx_tools.mrc /xdock alias to pass along $2-',
            'added DrawItemImage() for stacker to render the items image',
            'added mIRC_DrawText() function which draws a mIRC string using mIRC control codes',
            "changed IsFile() to do a file search before saying it can't access a file (allows it to find files in the system PATH)",
            'moved a whole bunch of functions out of misc.cpp and into mircFunctions.cpp or windowFunctions.cpp',
            'changed dcx_tools.mrc /return calls to /returnex',
            'added defines to TString such as SPACE, TAB, COMMA',
            'changed all controls to have an improved parseInfoRequest() that uses a TString prop instead of doing lots of gettoks',
            'changed some to_num() calls to to_int() when the number was typed as an int',
            'changed the $xpopup().style to use a switch statement instead of the ifs',
            'fixed statusbar $xdid().tooltip using gettok(3) when it should have been gettok(4)',
            'changed DrawParentsBackground() to only use dhwnd if it is not null',
            'changed WM_CTLCOLOR messages to set the background mode as TRANSPARENT and return a HOLLOW_BRUSH when the control hass WS_EX_TRANSPARENT set. this improves the look of some controls abit (exp radio or check)',
            'changed box to use a TString object from right after GetWindowText()',
            'changed to be always transparent',
            'moved DCXML out of dialog into its own section',
            'moved some defines to before the includes in defines.h to allow testing out the _SECURE_SCL 0 in the release builds',
            'toolbar changed to use MapWindowPoints() instead of ClientToScreen() and ScreenToClient()',
            'added NULL check to unregistreDefaultWindowProc()',
            'fixed memory leak in BitmapRegion()',
            'uncommented file access check from ChangeHwndIcon()',
            'changed some ifs in BitmapRegion() to make the meaning clear',
            'added a RGN_DATA count check before final create region',
            'fixed memory leak in background bitmap drawing',
            'changed all cursor code as needed to delete the LoadImage() cursor.',
            'fixed a small memory leak in BitmapRegion() when CreateDIBSection() fails.',
            'changed dcxLoadIcon() and ChangeHwndIcon() to take a flags argument',
            'Initialized some stacker vars to NULL',
            'changed radio WM_PAINT to set the text colours as set with xdid -C',
            'changed check WM_PAINT to set the text colours as set with xdid -C',
            'changed $xpopup().style to use a switch() instead of lots of ifs',
            'changed parseTrackFlags() to use a switch() instead of lost of ifs',
            'changed updateLayout() to return true/false to tell if it does anything or not',
            'changed button drawing code to check HDC is non-NULL before drawing bitmap',
            'fixed small memory leak in button bitmap drawing',
            'made getAnimateStyles() public',
            'added resizeBitmap() function. this resizes the supplied bitmap to matched the supplied RECT. if the resize works the old bitmap is deleted and the new one returned, otherwise the old bitmap is returned',
            'changed isPatched() function to be a const function',
            'added GetDXVersion() via getdxver.cpp. this is a function supplied by MS in its tutorials for getting the DirectX version. (dll needs to link with version.lib now)',
            'changed LoadDLL() to check for DirectX9 and set a variable if its found',
            'changed IsUsingDirectX function to check for DirectX version, function now replies with either the dx version or $false if no dx was found',
            'fixed small possible memory leak in trackbar custom drawing',
            'added showError() function to replace all other error display functions',
            'changed some error return codes to be 0 (halt)',
            'changed WM_HELP event to set itself as handled',
            'changed updateParentCtrl() to be a little bit faster when parent is dialog',
            'added CommonMessage() function to DcxControl class to handle WM_xxx messages that are common to all controls, like WM_HELP. DLL about 10k smaller',
            'changed SetupAlphaBlend() to pass on the client rect to DrawParentsBackground()',
            'changed to use TBSTYLE_xxx',
            'added WM_PRINTCLIENT to all controls, needed for AnimateWindow() and new transparency/alpha code',
            "changed DrawParentsBackground() to work in a manner similar to Vista's DrawThemeParentBackgroundEx()",
            'added getting DrawThemeParentBackgroundEx() from uxtheme.dll on Vista',
            'streamlined updateParentCtrl() function for new parent rendering method',
            'added DrawThemeParentBackgroundEx() usage on Vista to DrawParentsBackground()',
            'removed an unneeded updateParentCtrl() call in button control',
            'changed stacker item drawing code to move the right hand edge within the border',
            'added code to free uxtheme.dll on dll unload',
            'updated CreateGrayscaleIcon() to new code from The Code Project that supports 32bpp',
            'added InvalidateParentRect() which invalidates a controls area on its parent',
            'Tstring changed some compare operators to be constants',
            'Tstring changed the char[] operator to be const',
            'added DCX_USE_WINSDK to defines.h as a way to disable code dependant on the Windows SDK (Vista)',
            'fixed copyright from 2006 to 2006-2007',
            'added some comment sections to defines.h (getting real messy!)',
            'DLL now gets GetThemeBackgroundRegion() and GetWindowTheme() function pointers from uxtheme.dll',
            'added IsVistaStyle() function',
            'changed button background drawing to only be done within the WM_PAINT event',
            'added mIRCevalEX() which takes a formatted eval string',
            'changed themed drawing to Open/CloseThemeData() instead of doing GetWindowTheme() to help maintain the correct region',
            'streamlined listview/treeview sortItemsEx() and matchItemText()',
            'added SetupOSCompatibility()/FreeOSCompatibility() functions to handle getting function pointers',
            'changed AnimateWindow()/FlashWindowEx()/InSendMessageEx()/GetWindowInfo() calls to be function pointers. hopefully this should fix the win98 compatibility problems',
            'added getting DwmIsCompositionEnabled() function pointer. it is used to determine if user is on on Vista and if Aero is enabled',
            'added WINVER >= 0x600 checks to includes for theme stuff when compiling as Vista',
            'added WM_DWMCOMPOSITIONCHANGED define',
            'updated shadow code to match latest v03 from code project',
            'now disables shadows when on Vista and Aero is enabled',
            'lots of little changes/fixes for things only noticed with the Intel compiler',
            'made error messages look consistent across project',
            'created new dcx_demo.mrc that uses DCXML and showcases most of the controls',
            'added CreateHDCBuffer()/DeleteHDCBuffer() to create a temp HDC for buffered drawing',
            'changed some image SelectObject() calls to macros for the types',
            'most controls now use GDI+ to draw where possible',
            'added comment for CTLF_ALLOW_DOCK',
            'moved $shell alias from dcx_tools.mrc to dcx.mrc (which has a bunch of broken demos anyways)',
            'changed all SetWindowLong(.. GWL_WNDPROC,..) calls to be SetWindowLongPtr()',
            'added test code to listview NM_CLICK to allow selecting subitems (NEEDS TESTING, SUBJECT TO CHANGE/REMOVAL)',
            'added listview LVN_GETINFOTIP message handling to set tooltips',
            'changed treeview /xdid -w to only gettok the flags once',
            'added listview /xdid -r comment',
            'added SetVerbose() to dialog',
            'added IsVerbose() to dialog',
            'added error checking to treeview TNV_GETINFOTIP and TVN_SELCHANGED',
            'added note about this->getExStyle() in listview mode at top of source file',
            'listview grid style now redraws properly when scrolling',
        ),
        'Documentation' => array(
            'fixed errors in dcxdoc',
            'reworded stuff',
            'cleaned up some arrays so they look more consistant ',
            'fixed docs to work with php5 when short_open_tag is Off',
            'updated dcxvsmdx page',
            'fixed year of copyright to be dynamically generated by php (andy)',
            'removed a duplicate dcx_inc.php in /doc',
            'updated license files to 2007',
            'removed v1.4 comment (no such version yet)',
            'added writeDcxLoadIcon() to handle documentation for controls which use dcxLoadIcon',
            'added array_insert()',
            'fixed description for tab control',
            'fixed description of /xdialog -b +o',
            'fixed descriptions for /xdid -f CHARSET',
            'added a note for listview /xdid -Z',
            'fixed tutorial example missing a close-brace in xpopup page',
            'removed unecessary parameters in /xtray -d',
            "removed 'alpha' from events",
            'changed global style message to exlude embedded dialog/window controls',
            'added a note to comboEx styles to state the height is required for the dropdown',
            'uncommented multiple examples for $dcx(ColorDialog)',
            'moved some args to be arranged in alphabetical order',
            'fixed some broken wiki tags',
            'added xtreebar.php and xstatusbar.php',
            'removed "selstart" from statusbar properties (copy paste remnant)',
            'fixed grammar and reworded writing to be easier to understand on xdock page',
            'removed alot of unnecessary array declarations in $xdock properties',
            'added a note for all docking commands about dialogs within the INIT event',
            'fixed incorrect table tagging in credits section',
            'added notes about docking during dialog INIT in all /xdock docking functions',
            'moved part of image /xdid -o description to notes',
            'moved change log below callback section on index page',
            'renamed VALUE to PARAM on index page',
            "fixed a bug in /format_xcmd_header which caused examples with '0' values to be ignored",
            "updated 'owner' style description/notes for ColorDialog, OpenDialog, SaveDialog, FontDialog and MsgBox. They no longer support modeless owners because of FindOwner()",
            'updated return value to $null for OpenDialog, SaveDialog and FontDialog',
            'fixed description for ICON in listview /xdid -l',
            "fixed description for 'notrack' in listview trackbegin",
            'added diagonal examples to /xdialog -a, /xdid -h and /xdid -s',
            'added operating system note to /xdialog -a, /xdid -h and /xdid -s',
            'fixed section heading in xpopup page for Special menus and Xpopup item path',
            'fixed description for /xpopup -b only supporting BMP when GDI+ is not available',
            'fixed description for /xpopup -d, as it also removes menus with items in it',
            'fixed edit keyup and keydown events to include example',
            'fixed keyup typo',
            'cleaned /xdid -Z for richedit notes array',
            'updated list of controls available for /xdialog -c',
            'updated list of controls which box, divider, pager, panel, rebar and statusbar support',
            'changed the format which box, divider, pager, panel, rebar and statusbar list supported controls',
            'a list of these controls can be found at http://dcx.scriptsdb.org/controls.xls',
            'updated main page PARAM = $4-',
            'removed /xdid -l NSUB being 0-based index when it isnt',
            "added comment to 'editlabel' style in listview",
            'changed note for listview grid style',
            'removed +h copy paste remnant from note in listview /xdid -t (thanks hkr)',
            "fixed xdialog 'close' details and added 'scclose' events",
            'reworded parts of XTray Signals section',
            'added notes to dialog (embedded) control page and xdialog about closing docked dialogs within the close event',
            'added notes to dialog (embedded) control page and /xdialog about closing docked dialogs within the close event',
            'edited /xdialog -g comment about BMP files',
            'fixed stacker /xdid -a example and parameters',
            'added example for listview /xdid -j',
            'fixed listview seltext/pbar/keydown example',
            'commented out box checkchange event',
            'added error checking to see if examples exist when a command is set',
            "updated format_parameters() so it doesnt accept '0' as '__args'",
            'fixed ALOT of things in the docs such as missing parameters, outdated examples, inconsistancies with examples (big thanks to andy for spotting em out)',
            'moved directshow /xdid -V so its in alphabetical order',
            'removed a few redundant notes',
            'added missing examples for many events on numerous control pages',
            'fixed C:\mIRC\ error not displaying on a few pages, simply changed it to C:/mIRC/',
            'added note to listview labelbegin event',
            'reworded some events for scroll and trackbar',
            "added some notes for 'dl_progress' for webctrl",
            'renamed IS_ENABLED to ENABLED for webctrl events',
            'updated /xdid -Z on /xdid page',
            'removed /xdid -Z on listview page',
        ),
    ),
    'v1.3.7' => array(
        'New features' => array(
            'added $xpopup().isPatched',
            'added /xdialog -z, $xdialog().zlayer and $xdialog().zlayercurrent. Useful for creating tab-like pages for configuration dialogs and wizard type screens',
            'added $dcx(IsUnloadSafe)',
            'added new +x flag to /xdialog -b to enable composite rendering on XP+',
            'added $xdid(listview).columns',
            'added /xdid -i +s flag to set selection color for treeview',
            'added $dcx(IsUsingGDI)',
            'added $dcx(IsUsingDirectX)',
            'added alpha style for many controls',
            'added DirectShow',
            'added Stackerv',
            'added DateTimePicker',
            'added wordwrap support to transparent on text control',
            'added DCXML (still experimental)',
            'added $xdid(dname,id).alpha to tell if a control has the alpha style or not.',
            'added $xdock(mIRC).toolBarPos',
            'added $xdock(mIRC).treeBarPos',
            'added /xdialog -R dname +s which adds a shadow effect to the dialog',
            'added XTray',
            'added /xpopup -m mirc to patch mIRC allowing xpopup to work on mIRC 6.20',
            'added /xdock -F to set the treebar font, colors and styles',
            'added shadow style for many controls',
            'added support for combining regions via flags using /xdid -R and /xdialog -R',
            'added transparent global style',
            'added ghost drag for main mirc window via /xdock -G',
            'added ghost drag /xdialog -R dname +g',
            'added $xdid().range and .value to calendar',
            'modified $xdid(list).sel to include optional parameter N',
            'modified $xdid(listview).sel to include a new optional parameter N',
            'LoadDLL() now displays information related to dcx upon loadup if /debug is used in mIRC',
        ),
        'Fixes and changes' => array(
            '*** IMPORTANT *** image - changed /xdid -i to include flags',
            '*** IMPORTANT *** treeview - changed /xdid -a to include parameter for background color',
            '*** IMPORTANT *** calendar - changed calendar $xdid().selected to .value',
            'dialog - added max tooltip width of 400, this enables multiline tooltips by using $crlf in text.',
            'list - fixed memleak in $xdid().sel when n is not > 0',
            'progressbar - fixed a bug where some vars werent cleared on object creation.',
            'richedit - fixed memleak in $xdid().seltext',
            'image - fixed resizing bug',
            'added a check for invalid filename when loading icons',
            'list - changed $xdid().sel to limit the results length to 900',
            'listview - changed $xdid().sel to limit the results length to 900',
            'webcontrol - added error message to xdid -j when control isnt in ready state',
            'made WS_CLIPCHILDREN style apply to all controls',
            'webcontrol - changed it to be WS_CLIPSIBLINGS should help with some rendering issues',
            'xdock - changed DockWindow() to make parent window WS_CLIPCHILDREN and WS_CLIPSIBLINGS. this should help with rendering glitches',
            'changed gdiplus.dll to be a late loading dll to allow us to try & loading it without the dcx.dll failing to load completely. (this needs to be added to vs2003 project file)',
            'listview - fixed xdid -j bug where lviDcx wasnt checked for NULL',
            'listview - changed xdid -a to always add an lviDcx',
            'listview - removed duplicate code in xdid -a',
            'image - added setting the smoothing mode for gdi+ to aliased',
            'added error message to xdialog -R when a region couldnt be created',
            'Improved background rendering abit',
            'tab - added quick fix for tab closing when escape is pressed',
            'toolbar - fixed imagelist bug which caused display corruption',
            'tab - sclick now works for active item, and rclick work for inactive tabsv',
            'box - changed the drawing code abit to show the parents background abit better outside the box bounds',
            'fixed bug where tab control wasnt passing on child controls result codes',
            'richedit - fixed mem leak in $xdid().text',
            '$xdid().num on RichEdit now returns the real ammount of lines instead of always returning 1',
            'button - fixed BS_DEFPUSHBUTTON style not working',
            'listview - fixed rendering problem where item wouldnt be updated after being selected if a background picture was set',
            'listview - fixed /xdid -r bug that crashed mIRC',
            'toolbar - added error message for invalid flags symbol to xdid -w',
            'list - fixed mwheel support',
            'listview - fixed bug where you couldnt use /xdid -v on a listview item with a progressbar without it thinking it was a progressbar command, even if it was for a different subitem',
            'calander/datetime - fixed a bug where a TString object was used directly in an wsprintf instead of doing to_chr()',
            'readded quickfix for richedit excessive selchange',
            'changed calendar $xdid().selected to return 2 values even if not MULTI select',
            'changed Image to have auto image resize TRUE by default (this would break less scripts)',
            'renamed $xdock() functins to start with lower case (it was inconsistant with other property functions)',
        ),
        'Dcx code' => array(
            'changed dcxSetWindowTheme() to actually pass on the args to the theme dll',
            'set load->mKeep to TRUE',
            'changed some function args to be const',
            'dialog - changed tooltip hwnd check to use IsWindow() instead of != NULL',
            'dialog - added safeToCloseAll() function to dialogcollection.',
            'dialog - changed getName(), getAliasName() and getParentName() to return const refrences to the TString objects instead of new objects.',
            'dialog - small change to getDialogByName() to cast the TString object for compare.',
            'changed $xdid().pos & $xdid().dpos & $xdid().mouse to use MapWindowPoints() instead of ScreenToClient()',
            'dialog - rewrote DrawParentsBackground() to avoid creating an HDC unless it needs to, left commented old code in for refrence as this routine will need changed when/if we start giving ctrls bitmap backgrounds.',
            'dialog - changed $xdialog().mouse to use MapWindowPoints()',
            'dialog - changed DrawDialogBackground() to use client areas offsets instead of just zero.',
            'dialog - improved MakeShadow() by pre-calculating one of the PreMultiply() numbers instead of doing it within 2 loops.',
            'listview - changed $xdid().columns to use lstrcpyn() instead of wsprintf() when result is zero',
            'progressbar - changed WM_ERASEBKGND to render parents bkg when transparent',
            'image - changed /xdid -w to use MapWindowPoints()',
            'text - changed /xdid -w to use MapWindowPoints()',
            'added an extra error report to ChangeHwndIcon()',
            'changed ret() define to limit the copy to 900',
            'added an IsFile() check to dcxLoadBitmap()',
            'changed some parseGlobalInfoRequest() results to avoid buffer overflows',
            'changed defines.h to enable GDIPlus v1.1 specific stuff',
            'richedit - moved some vars in constructor',
            'statusbar - small change to $xdid().parts loop',
            'added IsFile() function to see if a file can be accessed or not',
            'added GetLastStatusStr() function to get string that go with GDIPlus error responses',
            'changed LoadDll() to place dll into non-gdi+ mode if GdiplusStartup() fails',
            'webcontrol - changed to use TString.to_wchr() where applicable',
            'listview - changed the constructor to insure that this control isnt WS_CLIPCHILDREN',
            'removed commented includes and constructors in most controls',
            'added new build called Development. This build is for dev releases & is the same as Release build except that it defines DCX_DEV_BUILD',
            'added a check for the avalibility of gdiplus.dll that sets a flag when the dll cant be loaded & displays a warning',
            'changed debug messages that rely on /debug on in mIRC to use a define DCX_DEBUG which can be easily switched to output nothing for the release builds',
            'tstring - added to_float() function to return the string as a double floating point number',
            'added DCXDebug(Cmd, Msg), similar to DCXError(Cmd, Msg)',
            'added DCX_USE_GDIPLUS define to control linking with gdiplus.lib (affects image & stacker controls)',
            'changed controlFactory() ctrl mask to be 64bit',
            'disabled the #4995 warning (name was marked as #pragma depricated)',
            'xdock - changed the rest of $xdock() to use a switch()',
            'changed SwitchbarPos() so it can be reused for the diff windows',
            'improved the prop handling a bit',
            'added dcxDrawShadowText() function & changed controls that support the shadow style to use it',
            'changed SetLayeredWindowAttributes to be an optional function pointer which is only used if its avail',
            'added WM_COMPAREITEM forwarding',
            'changed DrawParentsBackground() to use themes when it can, & to recurse when the parent its transparent',
            'added AggressiveOptimize.h to project',
            'changed mapfile code to detect mIRC 6.20 or 6.21+',
            'box - changed EnumBoxChildren() to only disable controls that are direct children of the box, not grandchildren',
            'tstring - changed to use CopyMemory()',
            'pager - removed WM_COLORDLG handling',
            'tstring - added to_wchr()',
            'change `sclick` & `rclick` callback events to be sent on mouseup',
            'box - commented BN_CLICKED message out',
            'text - fixed mem leak in wm_paint when transparent',
            'text - fixed styles when transparent, was hardcoded to be left',
            'tab - moved var to outside while loop in xdid -r code',
            'added DrawCtrlBackground() which handles drawing of a controls background',
            'changed DrawDialogBackgroundBitmap() to DrawDialogBackground(), now also handles background brush',
            'listview - added LVN_DELETEALLITEMS handling to listview to insure we always get an LVN_DELETEITEM message',
            'added getBgBitmap(), getBgTransparentCol(), & DrawDialogBackgroundBitmap() functions to dialog class',
            'changed /xdialog -g to call redrawWindow() instead of InvalidateRect()',
            'added getParentCtrl() & updateParentCtrl() functions to DcxControl class',
            'added AggressiveOptimize.h & some misc changes to compiler setting for VS2005 for a smaller dll size',
            'changed most controls to use dcxLoadIcon instead of ExtractIconEx()',
            'updated SystemTimeToMircTime() to include time',
            'listviews/treeview - changed regex search to handle commas in the text or regex pattern',
            'moved MircTimeToSystemTime() and SystemTimeToMircTime() to misc.cpp',
            'fixed typo in dcxdatetime.h checking wrong #IFNDEF',
            'changed alot of TString object = string; to TString object(string);',
            'changed treeviews getPathFromVector() to be a static function',
            'added checks to /xdock docking commands for window already being docked elsewhere',
            'added a check for invalid SYSTEMTIME values for SystemTimeToMircTime()',
            'fixed bug with List tbitem where it returns too many items',
        ),
        'Dcx Documentation' => array(
            'fixed dcxdoc quirk with dialog events given the ID 4',
            'removed a fixed string comparison for SECTION_INTRO',
            'added note for gdi+ loading multiple formats for image',
            'added note for gdi+ on index for where to download it',
            'added example to /xdid -R',
            'moved xpopup events upwards',
            'reworded and fixed example for /mpopup',
            'updated Dcx vs Mdx',
            'removed anchor from subcategory for changes.htm',
            'removed note for /xdid -i for image about only loading BMP files',
            'added CShadowHwnd to credits',
            'new logo',
            'altered documentation style sheet',
            'altered some quirks in dcx_inc.php',
            'fixed general typos and copy/paste errors found in the forums',
            'reworded recommendation in calendar and datetime intro',
            'added a little drawing bug notice to calendar intro',
            'removed link to dcx_old docs',
            'fixed up intro for calendar',
            'added note for calendar /xdid -m',
            'lower-cased first letter of all $xdock() functions',
        ),
    ),
	'v1.3.6' => array(
		'New Features' => array(
			'*IMPORTANT* added docking support! update your dcx_tools.mrc with the one supplied in the zip to include /xdock and $xdock',
			'*IMPORTANT* added /xdialog -T to create tooltips. must be done before using tooltips in your control!',
			'added pager control',
			'added "tooltips" style for button, ipaddress, pbar, richedit, updown, check, edit, image, link, radio, and text controls.',
			'added "balloon" style to listview and treeview (used with "tooltips" style)',
			'added new command /xdid -T to set the tooltip text for all controls which support the "tooltips" style.',
			'added $dcx(MsgBox)',
			'added caretpos property to edit and richedit control',
			'added gradient style to ProgressBars. use /xdid -c to set the start colour.',
			'added hover event to listview (only when hottrack is enabled)',
			'added /xdialog -w for setting icons to dialogs',
			'added dclick event to button control.',
			'added the ability to set the editbox contents in comboex control via /xdid -a',
			'added /xdialog -R to set a dialog regions (uses BitmapRegion() by David Gallardo Llopis)',
			'treeview, toolbar and tab tooltips now support tab characters',
			'added dclick event to listview even without an item selection',
			'added lbup and lbdown events for button',
			'added /dcx xSignal command to enable/disable the DCX signal (disabled by default).',
			'added sending of DCX signal for window resizing. See /dcx xSignal and XDock Signals for more information',
			'changed /xdialog -t command parameters to allow setting an alpha transparency level and transparent color',
			'added $xdialog().parent for docked dialogs (only works if they have been Mark\'d before docking)',
			'added "changing" callback event which can be used to stop a dialog being moved and/or sized by returning either "nosize" or "nomove" or "nochange"',
			'"nosize" no longer works for the "sizing" event',
			'added listview /xdid -n dname +s 0 flag to set column width to min required to show everything. (without enabling auto sizing)',
			'added autosize flags +a (autosize) +h (autoheadersize) +m (max size, max(autosize,autoheadersize)) to listviews /xdid -a command flags.',
			'added greyscale icon flag to button, listview, and toolbar controls',
			'added grayscale icon support to link, image, treeview, tab, statusbar, rebar, dialog, and comboex',
			'added rdclick event for right button double clicks on listview items.',
			'and some undocumented/reserved stuff for next release :)'
		),
		'Fixes and Changes' => array(
			'*IMPORTANT* changed /xdid -w syntax for many controls to be consistant (uses flags similar to /xdid -c)',
			'*IMPORTANT* changed message handling for all controls, should be much simpler and faster now :) (needs alot of retesting)',
			'*IMPORTANT* only use /xdialog -x to close marked dialogs within callback aliases. avoid using /dialog -x if possible.',
			"removed all auto resize flags from listviews /xdid -t command, as these don't work.",
			'reimplemented /xdid -r so it could be used with other commands',
			'changed m_tsToolTip to now be part of dcxcontrol.',
			'fixed richedit control was allocating memory for unneeded buffers for calllAliasEx() & never freeing them.',
			'changed xpopup does not work message slightly',
			'fixed richedit to use COLOR_WINDOWTEXT rather than a hardcoded black',
			'removed debug message when setting auto hyperlinking',
			'ignore repeats in richedit',
			'changed if-case flow to prevent valid /xdid calls from being classified as invalid',
			'changed a loop in function unfoldColor() to use mod for speed',
			'changed FindOwner() to use TString.',
			'fixed position of caret for richedit being reset when focus is set',
			'changed edit & richedit\'s $xdid().num to return 1 for single line controls.',
			'fixed bug with mwheel not ever showing down',
			'fixed bug in listview, forgot to add parseListviewExStyles() to second creator. (fixes fullrow select etc.. problems)',
			'changed listview sclick, rclick, dclick callbacks to also include subitem number',
			'moved code for comboex constructors into a single ConstructComboEx() function.',
			'fixed notheme not working correctly on comboex.',
			'changed tab controls "childid" info request to be an else if instead of just if',
			'fixed colorcombo selection not showing.',
			'changed WM_MEASUREITEM handling to support more ownerdraw controls in the future.',
			'fixed bug with box "bottom" style applying "none" instead',
			'moved RemStyles() & AddStyles() to misc.cpp',
			'added workaround for comboex edit box click lockup.',
			'fixed treeview item ordering bug.',
			'changed /xdid -c & /xdid -B to ensure the treeview item is visible.',
			'button control now shows text in COLOR_BTNTEXT instead of black and disabled button text in COLOR_GRAYTEXT',
			'/xdid -r for ipaddress doesnt need at least 1 parameter anymore',
			'changed LoadBitmap() to dcxLoadBitmap() to avoid confusion with built in function.',
			'added a check for parameter count for statusbar /xdid -k',
			'changed some instances of hard tab strings into soft tabs',
			'alot of box control custom draw changes',
			'improved the handling on transparency in box controls abit.',
			'added iswm() to TString.',
			'made "Dialogs" globally accessible through dcxDialogs()',
			'removed /clearall from /demo in dcx_demo.mrc',
			'added function mIRCSignal() to contain arguments',
			'changed some manual signal calls to use mIRCSignal()',
			'added function GetHwndFromString() to get dialog hwnds',
			'added va_end(args) to a few misc commands.',
			'added TString.to_num() and TString.to_int() functions',
			"fixed listview /xdid -n bug where column count wasn't 0 based.",
			"changed richedit's loadmIRCPalette() to not need lstrcpy().",
			'added autoSize() function to listview to size columns.',
			'fixed TString gettok(n,M,seps) bug (this also fixes the xpopups submenu items problem)',
			'fixed memory leak with CreateGrayscaleIcon()',
			'fixed memory leak with imagelists in toolbar',
			'initialised "m_bBitmapText" for button which is a child of another control',
			'added a macro to stop "unreferenced formal parameters" from being treated as an error in release build',
			'fixed uninitialised warning for Toolbar::setImageList()',
			'added TString.find()',
			'fixed memory leak with imagelists in listview',
			'fixed statusbar $xdid().text always returning text to first part.',
			'fixed statusbar $xdid().parts not working.',
			'fixed statusbar /xdid -y invalidating the image list.',
			"changed dll load function to check all functions before setting XPPlus, returns error if any aren't set correctly.",
			"added setting XPPlus to FALSE if the theme dll can't load.",
			'removed some testing code in dialog',
			'added control type to /xdid command error message',
			"added incRef(), decRef(), getRefCount() to dialog's along to checks to xdialog -x, to avoid closing a dialog with its own callback event. (still crashes with /dialog -x though)",
			'you can now use /xdialog -x within a callback (it handles timers for you)',
			'added WM_THEMECHANGED handling to box control.',
			"changed box control so it doesn't get the sys colour twice.",
			'richedit now supports xp themes (using CRichEditThemed class by Patchou)',
			'and MUCH MUCH MUCH ... MUCH MUCH more!',
		),
		'DCX Doc' => array(
			'removed downloads archive link from left menu',
			'updated dcx vs mdx page a bit (thanks Chrystoffer)',
			'thanks Andy for the help with dcxdoc for the Pager control',
			'added dclick to button events (thanks Andy)',
			'added the BSD license disclaimer',
			'changed wiki tag formatting code to be easier to maintain and more flexible',
			'added filesize to archive information',
			'added [n] and [f] wiki tags for dcxdoc (were missing and docs didnt process them)',
			'fixed typo in treeview dcxdoc',
			'updated num dcxdoc for edit and richedit',
			'fixed some confusing text in radio dcxdoc',
			'added gradient to pbar',
			'updated /xdid -c for pbar',
			'commented out support for [i]property[/i] tags in dcxdoc',
			'fixed xhtml validation for list of changes',
			'added valid css banner',
			'formatted some stuff in treeview doc',
			'changed the way dcxdoc generates files (easier to add new pages)',
			'reorganised dcxdoc functionality',
			'fixed some incorrectly labelled headings',
			'changed "XPopup Menus" link on left menu to "XPopup"',
			'small wiki tag changes to treeview',
			'fixed a whole bunch of [ID] confusion in various files',
			'fixed title bug "DCX DCX vs MDX"',
			'fixed various "WebControl" and "WebCtrl" inconsistancies',
			'cleaned up dcxdoc syntax generation',
			'added support for multiple examples in dcxdoc',
			'increased font size in dcxdoc by 1 point',
			'removed some manual "note" styles to use the proper wiki',
			'made the note on (docked) dialog intro more noticable and clear.',
			'added a note for "close" event on dialogs being sent twice',
			'download.php links to latest stable version correctly',
			'skips stable version in archive list',
			'removed link to index.htm for "DCX Controls" menu heading',
			'dcxdoc can now support multiple return values',
			'removed Webnet from dcxdoc credits, added forums and moved websites up over IRC',
			'added tutorials to dcxdoc',
			'added [code] wiki',
			'modified xpopup dcxdoc to use [code]',
			'removed old wiki code and some commented out headers',
			'removed old docs from repository',
			'moved alot of stuff from dcxdoc index page to dcx.htm, xdialog.htm and xdid.htm'
		),
	),
    'v1.3.5' => array(
        'DCX Changes' => array(
			'fixed bug that caused mIRC to crash when changing text in a listview when no progressbar exists',
			'fixed a bug where edit ctrl /xdid -o wouldnt accept 1 word',
			"added 'vertical' and 'verticalrev' styles to xpopup menus",
			'got calendar select date event working properly',
			'fixed a bug causing /xdid -Q not to update removal of bold and underline from treeview item',
			'added $xdid().mouseitem for toolbar',
			'changed the way /xdialog -g background image options work',
			'fixed crash on /dll -u when dcx dialogs open.',
			'fixed grid scroll redraw issue (flickers alot though)',
			'added $xdid().dname to dialog control to retrieve its original dialog name',
			'fixed ipaddress mouse click crash.',
			're-enabled ipaddress rclick & edit events.',
			'added sclick event to ipaddress controls.',
			'fixed corruption of toolbar button text when one is deleted (tooltip text still goes missing though)',
			'fixed button in tab crash.',
			'fixed edit control with text causing crash in tab & panel.',
			'added activate & deactivate events when dialog is activated & deactivated.',
			'keydown event no longer sends repeated keys (edit control)',
			'added arrow keys & caps lock to $dialog().key',
			'fixed GetTaskbarPos() bug where memory was never freed.',
			'added lbup event to image control',
			'removed same control checks from tab/panel, was causing a loop leading to stack overflow.',
			'fixed 2 memory leaks in calendar control.',
			'fixed xdid -U lockup, fixing this also solved many others.',
			"added 'rounded' style to box control.",
			'fixed webctrl activate crash bug.',
			'fixed comboex delete crashbug.',
			'/xdialog -d and /xdid -d (for panel/box) now removes control from internal list as well as destroying it.',
			'added mwheel event',
			'added /xdialog -j [id] support for individual control redraw',
			'added $xdialog().alias to retrieve alias function name',
			'added a check for existing alias upon marking',
			'made errors on marking more verbose',
			'fixed problem with listview extended styles being misapplied, causing listview to not appear when borderselect style is used',
			'added ability to set and retrieve tooltip background and text colors for toolbar.',
			'fixed toolbar bug that caused /xdid -c to always fail with invalid args error.',
			'added italics to treeview item styles',
			'added italic item support to listview',
			'fixed a bug with /xdid -k for richedit not applying background color to new text',
			'added balloon style to toolbar to be used with tooltips style to enable balloon tooltips.',
		),
        'DCX Project' => array(
			'removed "alias ttop" from dcx_demo.mrc (thanks TheShadowOne)',
			'general code reformatting in listview',
			'moved ExStyle to parseControlStyles for listview',
			'added function for grayscaling icons (incomplete)',
			'added dcx_VS2005.sln to compile under Visual Studio 2005',
			'added addtok() to tstring class',
			'added UNICODE listview declarations to define.h so there is no longer a need to edit internal Visual Studio files',
			'added sanity check to WindowProc for props existance.',
			'removed duplicate WS_CLIPCHILDREN style',
			'merged the 3 copies WM_MEARSUREITEM code into one.',
			'added sprintf function to TString.',
			'changed error responses to use TString.',
			'changed WM_DELETEITEM & WM_DRAWITEM messages to not use GetDlgItem().',
			'added check to panels WM_NOTIFY & WM_COMMAND messages to stop messages from itself.',
			'added code to attempt to get "mIRCN" mapfile when dll is loaded on mIRC V6.2+, otherwise old "mIRC" mapfile is used.',
			'removed alot of unneeded buffers used with callAliasEx().',
			'removed some commented out code.',
			'added checks for blocking messages.',
			'added code to add/remove WS_EX_CONTROLPARENT to parent controls as children are added/removed.',
			'starting to clean up code to make it more consistant',
			'fixed a few error message inconsistencies and typos',
			'removed some unecessary comments, includes, and variables',
			'added Ook to Version credits',
			'added an error message when /xdialog commands are invalid',
			'added invalid command message for /xdid',
			'changed some error messages to make them more consistant',
			'added check for WS_TABSTOP style in child before enabling WS_EX_CONTROLPARENT in parent control.',
			'moved listview extended styles parsing to its own function.',
			'fixed TBN_GETINFOTIP event in toolbar, was handled incorrectly.',
			'fixed TBN_DELETING event in toolbar, was deleting the wrong buttons data.',
			'removed a whole bunch of redundant assignments to variables to improve speed slightly',
			'removed some unreachable code',
			'added extra checks for uninitialised variables',
			'fixed a code flow bug in trackbar upon drawing the thumb when using bitmaps',
			'fixed bug in TString.istok() function which caused it to miss the last token.',
		),
        'DCX Doc' => array(
			'fixed a typo with /xdid -n for listview',
			'removed an unnecessary flag from /xpopup -i example in dcxdoc',
			'added daystate style and event to calendar control',
			"TODO: still a bug with dcxdoc where dialog events ID's are not 0",
			'added a few more people to the credits list',
			'added download.php',
			'included a reference to the version on changes.htm',
			'added an archive page',
			'incremented dcxdoc version to 1.3.5',
			'shifted some menu items for dcxdoc',
			'main download link now points to archive page',
			'added zipster to credits for testing',
			'changed the way some links worked for credits (tutorials)',
			"added link to EinsteinXXL's CLA tutorial",
			'added some comments at the end of long switch cases to make it easier to notice where they end',
			'fixed an error with /xpopup -x',
			'formatting of changes can now be structured to include categories',
			'added Ook to dcxdoc title',
			'script batch file now pauses to display output',
			'changed some credits titles',
			'updated screenshot for listview and treeview',
			'removed direct links to translation docs',
		),
	),
    'v1.3.4' => array(
		'modified dcx.mrc to include an image control which displayed an icon',
		'changed output of $xdid().hwnd from hex to decimal',
		'fixed a bug with bmp transparency for image control',
		'fixed a bug with background drawing for image control when no background color is set',
		'added update background image when dialog resized',
		'added $xdid().selrange to trackbar',
		'trackbar now flickers less',
		'added /xdid -g for trackbar to set images',
		'added /xdid -o for trackbar to set opacity color',
		"added 'transparent' style to text",
		'box now looks consistant with group box static controls',
		'(hopefully) fixed deletion of docked dialog bug causing mirc to crash (thanks HAPM)',
		"added 'none' style but removed 'squared' style for box control",
		'updated /xdid -C dcxdoc, +k flag no longer applies to box control border',
		'box control now draws text colors for enabled and disabled appropriately',
		'/xdid -k command for button control now only works for bitmap buttons to load bitmap images and set transparency color (Read function note for further details)',
		'moved some functionality of /xdid -k to /xdid -c for changing button control caption color',
		'fixed a bug causing toolbar separators not to apply hidden state when added',
		'added $dcx(IsThemedXP)',
		"added 'transparent' style to box control",
		'fixed bug with OpenDialog/SaveDialog functions returning error messages as values',
		'Added $xdialog(Name).ismarked to see if the name is marked already.',
		'fixed a richedit bug crashing on rapid doubleclicking',
		'fixed a bug with $xdialog().focusid when deleting a control with focus',
		'added lbdown, sclick, lbup, dclick and rclick events to box ctrl',
		'fixed tab focus into children of panel, rebar, box and docked dialog controls',
		'added event tracking to calendar (selchange, select, sclick)',
		'fixed bug to allow docked dialogs/@windows to be tabbed into as containers',
		'updated FontDialog dcxdoc to make more sense',
		'fixed a typo in dcxdoc /xdid -q incorrect, its meant to be /xdid -J for changing control cursors',
		'fixed grammatical errors with dcxdoc',
		'updated DCX vs MDX page (feel free to tell us when to change this, this page stands at a "super low never look at it until someone says something about it" priority)',
		'documented trackbar selrange features',
		'fixed dcxdoc typo for pbar',
		'added a note to dcxdoc stating the case sensitivity of script commands',
		'added missing example for sizing event on dialog dcxdoc',
		'fixed documentation for OpenDialog/SaveDialog Styles',
		'added note for dialog dcxdoc close event',
		'fixed error with dcxdoc for dialog events having wrong ID for example',
		'added /xdid -r to dcxdoc for comboex (missing)',
		'removed dclick event from calendar control (it just never occurred), and updated sclick event description',
	),
	'v1.3.3' => array(
		'added ability to change background color of trackbar (NOTE: there is a API bug to be aware of)',
		'implemented selchange and link events to richedit',
		'added /xdid -n to richedit to toggle automatic url hyperlinking',
		'added sclick and lbup events to richedit',
		'fixed a bug with richedit not accepting return keypresses when using multiline style',
		'fixed richedit $xdid().text bug not returning manually entered text',
		"added 'themechanged' event to dialog",
		'added /xdid -B to begin label editing mode on listview and treeview controls (NOTE: listview requires focus to begin editing)',
		'added progress bars to listview',
		'fixed dcxdoc errors (thanks dJabba, PYERO)',
		'fixed up events parameter values styling in dcxdoc',
		'minor adjustments to listview dcxdoc',
		'added dJabba and PYERO to dcxdoc credits',
	),
    'v1.3.2' => array(
		'Added /xdialog -t, and updated /xdialog -g to support background images',
		'Added /xdid -w to image control',
		'Added $xdid().font global function to retrieve the font in use with a control',
		'Fixed a bug causing FONTNAME to be an optional field with /xdid -f',
		'Fixed a bug causing /xdid -j to not work on edit ctrl',
		'Added $dcx(FontDialog)',
		'Added /xdid -t to panel',
		'Added link to old dcxdoc on \'latest changes\' description',
		'Changed /xdid -q to /xdid -Q for treeview item style changing command',
		'Implemented sclick event for treeview and listview when mouse clicked on no item',
		'Added quickfixes to ipaddress and comboex, to be drawn correctly when created with "disabled" style',
		'Added a quickfix for treeview icon 0 still showing first icon (will work as long as you dont use more than 10000 icons)',

		'Fixed typos, grammatical mistakes, inconsistancies, and missing features in dcxdoc with list ctrl dcxdoc (thanks elizio, dJabba, and MiSsInGnO)',
		'Added another tutorial link to cla page',
		'Fixed some styling',
		'Added /xdid -w to link control in dcxdoc, which was missing',
		'Fixed up example in /xdid -f dcxdoc to include CHARSET',
		'Readded Mpdreamz back to credits! oops! =P',
		'Changed contact irc network from IrcSuper to Americhat (stupid Shiek) =P',
		'Added a link to j0x\'s tutorial (french only)',
		'Fixed example with /xdid -C (rgb not showing)',
	),
    'v1.3.1' => array(
		'rewriting documentation, if you find any errors or inconsistancies with the old documentation, please post a message <a href="http://dcx.scriptsdb.org/forum/showthread.php?tid=171">here</a>',
		'fixed focus using tabbing on edit controls on dialog (box tabbing and focus still being researched)',
		'changed treeview and listview rclick events so it would fire even without an item being selected',
		'added a callback sclick when /xdid -c is called for comboex',
		'fixed a bug causing filters on Open/Save dialogs to be defaulted to "All Files"',
		'added /xdid -m switch to button control to allow text on bitmap buttons',
		'fixed a typo where /xdid -d wouldnt work for comboex',
		'added /xdid -o for pbar to make text vertical',
		'added/reimplemented dragbegin, dragfile, dragfinish events to comboex, dialog, listview, treeview, edit and listbox controls',
		'fixed a bug causing some listview items to ignore certain flags upon adding',
		'added GetTaskbarPos to retreive position of taskbar',
		'added /xdid -j to listview to change flags',
		'fixed box corner bug with colored background',
		'fixed bug that didnt let first toolbar button tooltip to be changed',
		'fixed a bug with /xdid -f not redrawing the control when the font is changed back to default',
	),
    "v1.3.0" => array(
		'fixed a display bug where text would be drawn off a button when too long',
		'added a pbar property $xdid().text',
		'added ability to set no text on a button using /xdid -t',
		'added keydown, keyup and return to richedit',
		'link font is now the system default GUI font',
		'fixed /xdid -C +k for box control not using the specified color',
		'added return and rclick event to richedit',
		'added /xdid -c to copy content to clipboard for edit and richedit ctrls',
		'added owner style to OpenDialog, SaveDialog and ColorDialog',
		'changed -C to -S for selecting text ranges in edit and richedit ctrls (this would of solved the coloring bug on these controls too)',
		'included a check on /udcx to see if it was called from a menu to prevent a crash on unload. please update your dcx_tools.mrc',
	),
	'v1.2.7 and v1.2.8 reimplementation' => array(
		'removed a debug output "Dialog WM_LBUTTONDOWN" when clicking on the dialog',
		'changed $dcx(GetSystemColor), please view documentation on changes to syntax',
		'added /xdid -o to overwrite a line for listbox ctrl',
		'added a style to the list control vsbar allowing it to be scrolled when overflowing',
		'added keydown and keyup events to edit ctrl',
		'added $dcx(ColorDialog), slightly changed syntax',
		'implemented $dcx(OpenDialog) and $dcx(SaveDialog)',
		'added selstart, selend, sel, seltext properties to edit ctrl',
		'added selstart, selend, sel, seltext properties to richedit ctrl',
		'fixed a bug in /xdid -d for tab ctrl where no page would be selected after deleting current page',
		'fixed a problem with box and link ctrls where cursor command /xdid -J wouldn\'t apply',
		'implemented /xdid -U for removing focus from a control. (will not work if there is only one control on the dialog)',
		'added nocut, nocopy and nopaste return values to prevent cut, copy and paste events for edit ctrl',
		'richedit editable by default',
		'added a style readonly to richedit',
		'added /xdid -Z for zooming richedit ctrls',
		'Please note that selchange (richedit) and dropfile events are missing.<br />
They will be reimplemented in the near future.',
	),

	'17/02/2006' => array(
		'Added /xdid -q and -m to the Listview for Group Support (XP+)',
		'Corrected the height of the colorcombo which is now the same as the comboex',
		'Fixed help file typos',
	),
	'16/02/2006' => array(
		'Added cursor stuff to the DLL via /xdialog -q and /xdid -J',
	),
	'15/02/2006' => array(
		'Added /xdialog -j',
		'Fixed richedit /xdid -k switch',
		'Fixed a drawing glitch on the box control',
	),
	'14/02/2006' => array(
		'Added the +ah flags to the /xdid -t command for listview headers',
		"Added /xdid -n to listview to resize header individually after they've been created",
		'Added $xdid().hwidth, .htext and .hicon to the listview',
		'Changed the range values of the trackbar to 32 bit values',
		'Fixed the fact that an undock dialog/@window was displayed when undocked even though it was hidden just before',
		'Fixed $xdid().tooltip on treeview that returned corrupted data',
	),
	'11/02/2006' => array(
		'Fixed a bug related to XPopup menus not showing properly after merger',
	),
	'02/02/2006' => array(
		'Merged XPopup to the DLL',
	),
	'01/02/2006' => array(
		'Added missing /xdid -d doc for the box control even though the function existed',
		'Added $xdid().tooltip to the toolbar control',
		'Fixed control deletion bug with "ghost" controls and invalid IDs, crashes, etc.',
		'Fixed potential problems with image lists on certain controls (not reported, but found by me)',
		'Fixed typos in the help file',
		'Fixed the TAB that made button text disappear bug',
		'Fixed the $xdid().icon treeview bug',
	),
	'31/01/2006' => array(
		'Added /xdid -o on the treeview to change the toltip text of an item',
		'Added the $xdid().mouseitem to the treeview control',
		'Added a Note to /xdid -p',
		'Added /xdid -k to richedit to change background color',
		'Added /xdialog -x which kills a dialog instead of triggering the close state',
		'Added the nosize return possibility in the sizing dialog event',
		'Fixed the $xdid().sel index being wrong on the comboex',
		'Fixed the link control refresh bug after /xdid -t',
		'Fixed $xdid().find in several controls generating a mIRC error when used with a $null value for matchtext',
		'Fixed /xdid -l for icon size not working for treeview',
		'Fixed /xdid -u not clearing selection in listview',
		'Fixed the header events not being sent when a listview was on a panel control (stupid API inconsistency here!)',
		'Modified the close event notice. A MUST READ',
	),
	'23/01/2006' => array(
		'Added /xdid -v to change a celle text on statusbar',
		'Added the dialog name in some error messages',
		'Changed the updown $xdid().pos to $xdid().value',
		'Fixed a typo in the scroll "vertical" style preventing is from working',
		'Corrected typos in the help file',
	),
	'11/01/2006' => array(
		'Added /xdialog -f to flash dialog windows',
		'Reduced the height of the colorcombo control',
	),
	'09/01/2006' => array(
		'Added $xdid()ispass to the edit control',
		'Added /xdid -j to the edit control to trigger password mode',
		'Fixed a toolbar icon list bug',
		'Fixed the ready state of the webctrl when created, it now browses to about:blank',
		'Fixed the rebar refresh problem linked to CLA',
	),
	'08/01/2006' => array(
		'Fixed the WebCtrl GPF Bug that afflicted it so hard only on certain machines',
		'Added scrollend event to the listview',
		'Added $xdid().tbitem to listview (Mpdreamz :P)',
		'Added $xdid().mouseitem to listview (Mpdreamz :P)',
		'Increased the maximum limit of text in the edit control',
		'Fixed typos in the help file and added docs on some features and styles',
	),
	'07/01/2006' => array(
		'Added $xdialog().id to retrieve the Nth used id in a dialog',
		'Added $xdid().type to retrieve the type of the control',
		'Added hrclick event for headers in the listview',
		'Added $xdid().inbox to the box control that gives the interior client area that clears the box border + text',
		'Added sclick, lbup, lbdown, lbdclick and dclick events to the panel',
		'Added /xdid -q to change the tooltip on a toolbar button',
		'Added the squared style to the box',
		'Added $xdid().childid on tab and rebar',
		'Added dialog docking on panel and box controls',
		'Added xdid -d on panel and box controls to delete child controls',
		'Replaced the noresize and noparentalign styles by noauto in the toolbar which combines both together',
		'Changed the box so that the text background color is now the line color and text color can be different from line',
		'Fixed a Richedit coloring bug',
		'Fixed xdid -t on the listview',
		'Fixed Image control refresh bug',
		'Fixed the /xdid -c and selection bug in the colorcombo',
		'Fixed a bug with the $xdid().find in the comboex',
		'Fixed a bug where header events were not triggered when the listview was on a divider',
		'Fixed the /xdid -j treeview bug',
		'Fixed typos in the help file',
	),
	'03/01/2006' => array(
		'Added /xdid -j on trackbar (Only works with XP themes disabled)',
		'Added $xdid().dpos giving position relative to dialog',
		'Changed $xdid().pos giving position relative to parent (which can also be the dialog)',
		'Fixed /xdid -f for the richedit',
		'Fixed $xdid().pid bug',
		'Fixed the Edit $xdid().text not returning correct value in the "edit" event',
		'Fixed CLA GPF bug',
	),
	'17/12/2005' => array(
		'Added ans extra parameter to the /xdid -j of the treeview for the selected icon',
		'Corrected the $xdid().seltext not working properly on the treeview',
	),
	'16/12/2005' => array(
		'Fixed Comboboxex edit control not supporting more than the combo width of characters.',
	),
	'15/12/2005' => array(
		'Rebuilt the box control to make it custom which reduces problems and makes it support colors for the line',
		'Changed the box style rjustify to right and added the bottom style',
		'Added $xdid().tooltip to treeview',
		'Added /xdid -i for the toolbar to change the button icon',
		'Fixed toolbar dropdown event bug',
	),
	'14/12/2005' => array(
		"Converted the box control to a CONTAINER control like the PANEL so people can use the CLA with it's controls inside",
		'Added $xdialog().key general property',
		'Added $xdid().pid general property',
		'Added lbup, lbdown, lbdblclk, rbup, rbdown, rbdblclk, mbup, mbdown, mbdblclk events to dialog',
	),
	'11/12/2005' => array(
		'Corrected the mIRC Controls not working properly when the dialog is marked bug',
	),
	'10/12/2005' => array(
		'Added sclick and rclick events on some controls where it was missing and useful.',
		'Added $xdialog().mouse and $xdid().mouse',
		'Added the W and H to the sizing dialog event',
		'Added $xdid().icon to Toolbar, ListView, TreeView and Tab controls',
	),
	'09/12/2005' => array(
		'Added /xdid -c to change button color/styles on toolbar',
	),
	'08/12/2005' => array(
		'Moved /xdid -l to /xdid -j on treeview',
		'Added /xdid -l to change icon size on treeview',
		'Added /xdid -g to change item height on treeview',
		'Added /xdid -u to change toolbar button size',
		'Added /xdid -v to change toolbar button text',
		'Corrected a bug in the /xdid -p no refreshing the child controls',
	),
	'07/12/2005' => array(
		'Corrected typos in the edit and richedit control help',
		'Corrected a bug in the toolbar /xdid -l that did not refresh the bar buttons',
	),
	'06/12/2005' => array(
		'Corrected the /xdid -x | /xdialog -b border bugs',
		'Corrected a bug in the /xdid -p not refreshing the control properly',
	),
	'05/12/2005' => array(
		'Added the $xdialog().mouseid which returns over which control ID the mouse is.',
		'Added the focus and focusout dialog events which indicate when a control has focus or when it loses it.',
		'Added the $xdialog().focusid which returns which control has the focus.',
		'Corrected the box control repainting child controls\' border bugs',
	),
	'04/12/2005' => array(
		'Added /xdid -Z vertical scrolling function that can be used in any control',
		'Added an extra parameter [CHARSET] to the /xdid -f font command',
		'Added font change support on the progressbar',
		'Added +es switched to a treeview item being added',
		'Added mouse events mouse, mouseenter and mouseleave',
		'Reverted the Image control to BMP only because of problems with the GDI+ lib, so only BMPs are supported now with a color for transparency',
		'Corrected a drawing bug with the Image control when it was resized using the CLA',
	),
	'03/12/2005' => array(
		'Added $xdialog().ismenu',
		'Added the /xdid -F focus on control',
		'Added error messages for commands that create other controls when the ID is already used : /xdialog -c : Control with ID "4" already exists',
		'Added /xdid -t/-u on the edit and richedit to load from/save to a file',
		'Corrected the $xdid().num and .state on the listview',
		'Corrected the box control repainting child controls bugs',
		'Corrected the $xdid().text from edit not returning the correct value',
	),
	'29/11/2005' => array(
		'Added $xdid().text property to the toolbar',
		"Corrected a bug with the @window not properly setting it's control ID when docked",
		'Added $xdid().hwnd general control property',
	),
	'28/11/2005' => array(
		'Added the Web control',
		'Added the DCX vs MDX comparison page',
	),
	'27/11/2005' => array(
		'Added @window docking support on the panel control',
		'Added omitted updown control styles from help',
	),
	'26/11/2005' => array(
		'Added the IP Adress control',
		'Added the Updown control',
		'Corrected a GPF in the Cell Layout Algorithm (CLA) when supplied a bad cell path: now issues an error message',
		'Corrected the transparency/flat toolbar bug when a child control of a panel',
	),
	'25/11/2005' => array(
		'Fixed panel child controls not returning events for some controls',
		'Fixed bug related to toolbar button click GPF',
		'Fixed icon bug on listview',
		'Added information on icon space and [INDENT] param in N.B.s in listview doc',
		'Modified list of accessible controls by tab and divider controls to generic resizeable controls to prevent problems',
		'Fixed hsclick/hdclick events in listview missing in tab/divider/rebar child listviews',
		'Fixed the stateclick state bug by returning the correct state value in the event',
		'Added size 24 icons to the toolbar icon size command',
	),
	'24/11/2005' => array(
		'Added tracking event on the trackbar',
		'Changed the sclick event of the toolbar',
		"Rebar's /xdid -q feature has been disabled until I find a way to achieve this if it's possible",
	),
	'23/11/2005' => array(
		'Added Regular Control: Image; with support for PNG, JPG, GIF, BMP and transparency.',
		'Added Edit Events: return, edit',
		'Added missing feature to get text of combo editbox in $xdid().text',
		'Added /xdid -v t the divider to set the bar position',
		'Fixed $xdialog().nextid bug',
		'Fixed the /xdid -p bug not working on docked @window and dialog',
		'Corrected typos in the help file',
	),
	'21/11/2005' => array(
		'Added Regular Control: Link',
		'Corrected typos in the help file',
	),
	'17/11/2005' => array(
		'Added Regular Control: Listbox',
		'Rewrote my test dialog separating each control into a single command for quick enabling/disabling of a particular control',
	),
	'16/11/2005' => array(
		'Resolved a listview /xdid -a where N=0 end insertion did not work for icon, smallicon and list styles',
	),
	'13/11/2005' => array(
		'Added Regular Control: scrollbar',
		'Added multiple ID support for /xdid',
		'Added /xdialog -g, /xdid -C color commands',
		'Corrected a treeview checkbox style bug preventing checkboxes to be used in the treeview',
	),
	'11/11/2005' => array(
		'Added Regular Controls: edit, text',
		'Corrected typos in help',
		'Removed some debug messages not used',
	),
	'10/11/2005' => array(
		'Fixed the panel control not being created properly and acting as a divider',
		'Added Regular controls : Line, Box, Radio and Check',
		'Corrected a bug in the toolbar/statusbar/rebar controls not being asserted their top/bottom/left/right automatic positions in the panel control',
		'Corrected rebar band release display bug',
	),
	'09/11/2005' => array(
		'Activated /xdid and $xdid for docked @windows and dialogs',
		'Added the default style for the button',
		'Added general control styles: tabstop, group, disabled',
		'Changed help files in styles section',
	),
	'02/11/2005' => array(
		'Added a notice for switches +mn of the /xdialog -b command',
	),
	'14/10/2005' => array(
		'Corrected a GPF bug when the DLL was unload via /dll -u and a DCX dialog is opened',
	),
	'10/10/2005' => array(
		'Changed labeltip to tooltip in Listview styles',
		'Added /xdid -f font command to the richedit control',
		'Added /xdid -M global control command linked with $xdid().mark to store additional information per control',
		'Added toolbar AutoStretch buttons feature linked with /xdid -m',
		'Added demo dialog which needs to be completed',
		'Added change rebar event',
		'Added an important note to /xdialog -l',
	),
	'09/10/2005' => array(
		'Added Tab Control',
		'Corrected Typos in help files',
	),
	'08/10/2005' => array(
		'Added Panel Control',
	),
	'07/10/2005' => array(
		'Relaxed compilation options hopefully to resolve the $dll unable to open dcx.dll problems',
		'Added the /xdialog -l command',
		'Added a new section - Cell Layout Algorithm',
	),
	'20/09/2005' => array(
		'Added fixedorder style to rebar control',
		'Fixed button /xdid -l and -t help file examples',
	),
	'20/09/2005' => array(
		'Added Event Management in the divider control for subcontrols',
		'Corrected the WIDTH param in the rebar not taken into account on band creation',
	),
	'19/09/2005' => array(
		'Added the custom made divider control (not fully functional yet, misses event handling of child controls)',
		'Corrected typos in the help file',
	),
	'17/09/2005' => array(
		'Added option to set separator width in toolbar in /xdid -a notes',
		'Corrected .selext & .text comboex bugs',
	),
	'16/09/2005' => array(
		'Corrected a bug in my TString support lib also related to the richedit bug',
		'Added multiline selection in listview + $xdid .selnum and modified .sel prop',
		'Added more listview optional control styles',
		'Added top, noresize, noparentalign statusbar styles',
		'Added dialog events, endsize, min, max, restore, beginmove, moving, endmove',
	),
	'14/09/2005' => array(
		'Added /xdid -l to ListView + TreeView to change icon',
		'Added /xdid -v to ListView',
		'Corrected explanation for the progressbar "digital mode"',
	),
	'13/09/2005' => array(
		'Corrected a treeview itempath bug',
	),
	'11/09/2005' => array(
		'Corrected typo in Mark Command',
	),
	'7/09/2005' => array(
		'Corrected a toolbar tooltip bug',
		'Corrected the toolbar font not being applied',
		'Correctd help typos',
		'Let me kwow if anyone has problems with the Release DLL',
	),
	'5/09/2005' => array(
		'Completed RichEdit control',
		'Added .isid and .nextid $xdialog properties',
		'Corrected typos in help file',
		'Help file now being translated into French, Swedish, Portuguese and Finnish. Looking for translators for Spanish and Italian.',
	),
	'4/09/2005' => array(
		'Added the Button control',
		'Documented help event in all controls',
		'Corrected a few typos in the help file',
	),
	'3/09/2005' => array(
		'Added $xdid .find prop to ListView',
		'Rebuilt the /xdid -z of TreeView with more sorting options',
		'/xdid -f Font change switch completed',
	),
	'2/09/2005' => array(
		'Added /xdid -g, -i and -z switches to ListView',
		'Added .tooltip prop to statusbar',
	),
	'1/09/2005' => array(
		'Added -v switch to treeview to change itemtext',
		'Finished code base adaptation',
	),
	'31/08/2005' => array(
		'Added -j switch on toolbar to set button min and max width',
	),
	'28/08/2005' => array(
		'Mark function parameters changed',
		'Added Text on the Progressbar control',
		'Added 3 events on progressbar, sclick, rclick and mousebar',
		'Typos in help files',
	),
	'25/08/2005' => array(
		'Recoded the whole base of the framework for better evolution in the futur',
		'Need to convert old code to new franework, not hard but time consuming',
	),
	'23/08/2005' => array(
		'Added Colorcombo control completed',
		'Started RichEdit control, but far from finished',
	),
	'21/08/2005' => array(
		'Major Changes',
		'DCXControl was transfered to /xdialog -c',
		'Added several /xdialog switches',
		'Moved Animate to /xdialog',
		'Added several Rebar /xdid switches',
		'Added rebar events',
		'Added COLOR support for rebar band text',
		'Corrected help file documentation and typos',
	),
	'18/08/2005' => array(
		'Added more child controls on rebar',
		'Activated events on child controls on rebar',
		'Added /xdid switches for rebar control',
	),
	'16/08/2005' => array(
		'Dialog events with beginsize and sizing',
		'Added rebar functionnality ( more to come )',
		'Corrected a toolbar GPF bug',
		'Added some event support for child controls on rebar',
	),
	'14/08/2005' => array(
		'Changed the pbar /xdid -mf switch to -mg',
		'Started Rebar Control (really incomplete)',
		'Corrected help file typos',
	),
	'13/08/2005' => array(
		'Added /xdialog and $xdialog functions',
		'Added -b switch to /xdialog for border/style mods on dialogs',
		'Added -x general switch to /xdid',
		'Finally resolved mIRCs trick in disabling dialog resizing, now functional without needing an extra control (hint: positioner).',
		'Added Item number returned in $4 in sclick, stateclick, rclick and dclick events of listview',
	),
	'06/08/2005' => array(
		'Added Trackbar control',
		'Added documentation warning in @window doc',
		'Updated DLL Documentation with HTML fixes and corrections of all kinds',
	),
	'02/08/2005' => array(
		'Bug Fixes',
	),
	'01/08/2005' => array(
		'Added @window docking',
		'Added Animate Dialog Function',
		'Added Toolbar Control',
		'Debugging/Cleaning of debug echos (If you see some more debug text, please let me know)',
	),
	'31/07/2005' => array(
		'Added ComboEx Control',
		'Added Listview more stuff',
	),
	'26/07/2005' => array(
		'Added ListView (really not finished)',
	),
	'24/07/2005' => array(
		'Added Statusbar control',
	),
	'17/07/2005' => array(
		'Added treeview /xdid switches',
	),
	'16/07/2005' => array(
		'Changed the progressbar /xdid -s switch to -u',
		'Added /xdid global switches, -behps',
		'Added $xdid() global props, .enabled, .visible, .pos',
		'Added treeview $xdid() properties',
	),
	'14/07/2005' => array(
		'Added all the treeview events',
		'Added a couple -X switches to the treeview control',
	),
	'13/07/2005' => array(
		'Changed the progressbar /xdid -b switch to -k',
		'Added start of treeview control (rest is coming)',
	)
);
?>
